In [1]:
import pandas as pd
import numpy as np
import os,glob,nrrd
from tqdm import tqdm

In [2]:
anno,header = nrrd.read("..\\CLA\\annotation_10.nrrd")
dfarea = pd.read_excel("..\\CLA\\brain_areas.xlsx")

In [3]:
neurons = glob.glob(r"J:\BLA_four_types\BLA_swc_mirrow\*")

In [5]:
# 转 neuron为不同edge  CA1 限定
# neurons = glob.glob(r"H:\20230302_figs\20230303_POA_VMH_combine\swc\*")
dfcsvpath = r"J:\BLA_four_types\all_csv2"
dfcombine = pd.read_excel(r"D:\python\pre-cube length\level_8_map_cortex friendly_change_swc.xlsx",index_col=0)
subarea = dfcombine.child.to_list()
def get_branth(x):
    global bratch_ID
    tmp = x.parent - x.ID
    if tmp < -2:
        bratch_ID += 1
    return bratch_ID

def get_side(x):
    if x.ML <= 5700:
        return "left"
    else: 
        return "right"

def get_area_ID(x):
    try:
        area_ID = anno[round(x.AP/10),round(x.DV/10),round(x.ML/10)]
        return area_ID
    except:
        return 0

def get_area_name(x):
    if x.area_ID !=0:
        area_name = dfarea.loc[dfarea.ID == x.area_ID].region.values[0]   
        return area_name
    else:
        return "unname"

def get_name_use(x):
    if x.area_name !="unname":
        if x.area_name in subarea:
            name_use = dfcombine.loc[dfcombine.child == x.area_name,"father"].tolist()[0]  
            return name_use
        else:
            return x.area_name
    else:
        return "unname"


for neuron in tqdm(neurons):
    # print(neuron)
    file = neuron.split("\\")[-1].split(".")[0]
    dfneuron = pd.read_csv(neuron,sep = " ",header= None)
    dfneuron.columns = ["ID","type","AP","DV","ML","R","parent"]
    dfneuron.loc[:, "area_ID"] = dfneuron.apply(get_area_ID, axis=1)
    dfneuron.loc[:, "area_name"] = dfneuron.apply(get_area_name, axis=1)
    dfneuron.loc[:, "name_use"] = dfneuron.apply(get_name_use, axis=1)
    # dfneuron.loc[:, "in_not"] = dfneuron.apply(get_in_or_not, axis=1)
    soma = dfneuron.loc[dfneuron.parent == -1].name_use.values[0]
    bratch_ID = 1
    dfneuron.loc[:, "bratch_ID"] = dfneuron.apply(get_branth, axis=1)
    # dfneuron.loc[:, "area_ID"] = dfneuron.apply(get_area_ID, axis=1)
    # dfneuron.loc[:, "area_name"] = dfneuron.apply(get_area_name, axis=1)
    
    dfneuron.loc[:, "side"] = dfneuron.apply(get_side, axis=1)
    dfneuron.to_csv(os.path.join(dfcsvpath,file+".csv"))

100%|██████████| 92/92 [06:31<00:00,  4.25s/it]

In [ ]:
# 转 neuron为不同edge
# neurons = glob.glob(r"H:\20230302_figs\20230303_POA_VMH_combine\swc\*")
dfcsvpath = r"J:\260228_Hip\all_csv"
dfcombine = pd.read_excel(r"D:\python\pre-cube length\level_8_map_cortex friendly_change_swc.xlsx",index_col=0)
subarea = dfcombine.child.to_list()
def get_branth(x):
    global bratch_ID
    tmp = x.parent - x.ID
    if tmp < -2:
        bratch_ID += 1
    return bratch_ID

def get_side(x):
    if x.ML <= 5700:
        return "left"
    else: 
        return "right"

def get_area_ID(x):
    try:
        area_ID = anno[round(x.AP/10),round(x.DV/10),round(x.ML/10)]
        return area_ID
    except:
        return 0

def get_area_name(x):
    if x.area_ID !=0:
        area_name = dfarea.loc[dfarea.ID == x.area_ID].region.values[0]   
        return area_name
    else:
        return "unname"

def get_name_use(x):
    if x.area_name !="unname":
        if x.area_name in subarea:
            name_use = dfcombine.loc[dfcombine.child == x.area_name,"father"].tolist()[0]  
            return name_use
        else:
            return x.area_name
    else:
        return "unname"


for neuron in tqdm(neurons):
    # print(neuron)
    file = neuron.split("\\")[-1].split(".")[0]
    dfneuron = pd.read_csv(neuron,sep = " ",header= None)
    dfneuron.columns = ["ID","type","AP","DV","ML","R","parent"]
    # dfneuron.loc[:, "in_not"] = dfneuron.apply(get_in_or_not, axis=1)
    bratch_ID = 1
    dfneuron.loc[:, "bratch_ID"] = dfneuron.apply(get_branth, axis=1)
    dfneuron.loc[:, "area_ID"] = dfneuron.apply(get_area_ID, axis=1)
    dfneuron.loc[:, "area_name"] = dfneuron.apply(get_area_name, axis=1)
    dfneuron.loc[:, "name_use"] = dfneuron.apply(get_name_use, axis=1)
    dfneuron.loc[:, "side"] = dfneuron.apply(get_side, axis=1)
    dfneuron.to_csv(os.path.join(dfcsvpath,file+".csv"))

100%|██████████| 192/192 [47:33<00:00, 14.86s/it]

In [6]:
%reset

In [6]:
files = glob.glob(r"J:\BLA_four_types\all_csv2\*")
outpath = r"J:\BLA_four_types\csv_new"
os.makedirs(outpath,exist_ok=True)

for filetmp in tqdm(files):
    dftmp = pd.read_csv(filetmp,index_col=0)
    filename = filetmp.split("\\")[-1]
    inlist = dftmp.parent.unique()
    IDlist = dftmp.ID.tolist()
    dftmp["terminal"] = [0 if item in inlist else 1 for item in IDlist]
    dftmp.to_csv(os.path.join(outpath,filename))

100%|██████████| 92/92 [00:27<00:00,  3.39it/s]

In [ ]:
## get terminal infor
files = glob.glob(r"J:\BLA_Cck\csv_new\*")
for file in files:

In [13]:
dftmp.type.value_counts()

2    57535
3     3410
1        1
Name: type, dtype: int64

In [14]:
dftmp.loc[dftmp.terminal == 1].type.value_counts()

2    337
3     62
Name: type, dtype: int64

In [17]:
# dftmp = dftmp.drop("Unnamed: 0.1",axis=1)
dftmpnew = dftmp.loc[dftmp.terminal == 1]
dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
filename = filetmp.split(".")[0]
dftmpnew["filename"] = filename

C:\Users\zljia\AppData\Local\Temp\ipykernel_281688\768861316.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_281688\768861316.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_281688\768861316.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_281688\768861316.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename

In [18]:
dftmpnew

,ID,type,AP,DV,ML,R,parent,bratch_ID,area_ID,area_name,name_use,side,terminal,soma_AP,soma_DV,soma_ML,filename
313,314,3,7476.36,6618.32,2189.66,0.378906,313,11,451,BLAv,BLA,left,1,7412.1,6568.3,2227.68,J:\BLA_Cck\csv\252578_033
464,465,3,7280.50,6569.82,2217.38,0.324219,464,19,451,BLAv,BLA,left,1,7412.1,6568.3,2227.68,J:\BLA_Cck\csv\252578_033
528,529,3,7534.78,6624.58,2271.40,0.007812,528,26,451,BLAv,BLA,left,1,7412.1,6568.3,2227.68,J:\BLA_Cck\csv\252578_033
582,583,3,7460.62,6499.12,2248.60,0.406250,582,28,451,BLAv,BLA,left,1,7412.1,6568.3,2227.68,J:\BLA_Cck\csv\252578_033
673,674,3,7474.12,6532.08,2112.84,0.296875,673,31,451,BLAv,BLA,left,1,7412.1,6568.3,2227.68,J:\BLA_Cck\csv\252578_033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60390,60391,2,5798.02,6244.84,7568.92,0.296875,60390,783,298,MA,MA,right,1,7412.1,6568.3,2227.68,J:\BLA_Cck\csv\252578_033
60670,60671,2,6595.60,5804.48,8736.42,0.648438,60670,785,303,BLAa,BLA,right,1,7412.1,6568.3,2227.68,J:\BLA_Cck\csv\252578_033
60933,60934,2,6613.84,6071.88,8822.94,0.406250,60933,786,303,BLAa,BLA,right,1,7412.1,6568.3,2227.68,J:\BLA_Cck\csv\252578_033
60936,60937,2,5671.34,6270.72,7533.28,0.570312,60936,787,298,MA,MA,right,1,7412.1,6568.3,2227.68,J:\BLA_Cck\csv\252578_033
60945,60946,2,5653.70,6281.14,7541.94,0.191406,60945,788,298,MA,MA,right,1,7412.1,6568.3,2227.68,J:\BLA_Cck\csv\252578_033

In [7]:
## combine csv files
os.chdir(r"J:\BLA_four_types\csv_new")
files = os.listdir()

In [25]:
dftmpnew

,ID,type,AP,DV,ML,R,parent,bratch_ID,area_ID,area_name,name_use,side,terminal,soma_AP,soma_DV,soma_ML,filename
313,314,3,7476.36,6618.32,2189.66,0.378906,313,11,451,BLAv,BLA,left,1,7412.1,6568.3,2227.68,252578_033
464,465,3,7280.50,6569.82,2217.38,0.324219,464,19,451,BLAv,BLA,left,1,7412.1,6568.3,2227.68,252578_033
528,529,3,7534.78,6624.58,2271.40,0.007812,528,26,451,BLAv,BLA,left,1,7412.1,6568.3,2227.68,252578_033
582,583,3,7460.62,6499.12,2248.60,0.406250,582,28,451,BLAv,BLA,left,1,7412.1,6568.3,2227.68,252578_033
673,674,3,7474.12,6532.08,2112.84,0.296875,673,31,451,BLAv,BLA,left,1,7412.1,6568.3,2227.68,252578_033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60390,60391,2,5798.02,6244.84,7568.92,0.296875,60390,783,298,MA,MA,right,1,7412.1,6568.3,2227.68,252578_033
60670,60671,2,6595.60,5804.48,8736.42,0.648438,60670,785,303,BLAa,BLA,right,1,7412.1,6568.3,2227.68,252578_033
60933,60934,2,6613.84,6071.88,8822.94,0.406250,60933,786,303,BLAa,BLA,right,1,7412.1,6568.3,2227.68,252578_033
60936,60937,2,5671.34,6270.72,7533.28,0.570312,60936,787,298,MA,MA,right,1,7412.1,6568.3,2227.68,252578_033
60945,60946,2,5653.70,6281.14,7541.94,0.191406,60945,788,298,MA,MA,right,1,7412.1,6568.3,2227.68,252578_033

In [8]:
dfall = pd.DataFrame()
for filetmp in files:
    dftmp = pd.read_csv(filetmp,index_col=0)
    # dftmp = dftmp.drop("Unnamed: 0.1",axis=1)
    dftmpnew = dftmp.loc[dftmp.terminal == 1]
    dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
    dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
    dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
    filename = filetmp.split(".")[0]
    dftmpnew["filename"] = filename
    # dftmpnew["geno"] = filename.split("_")[2]
    # dftmpnew["geno"] = filename.split("_")[2]
    dfall = pd.concat([dfall,dftmpnew],axis=0)

C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_ML"] = dftmp.iloc[0,:].ML
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["filename"] = filename
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_AP"] = dftmp.iloc[0,:].AP
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dftmpnew["soma_DV"] = dftmp.iloc[0,:].DV
C:\Users\zljia\AppData\Local\Temp\ipykernel_21532\1152209363.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead


In [9]:

dfall.to_csv("..//all_terminal_infor_combine.csv")

In [41]:
dfall["name_side"] = dfall["name_use"]+"_"+dfall["side"]

In [42]:
dfall

,ID,type,AP,DV,ML,R,parent,bratch_ID,area_ID,area_name,name_use,side,terminal,soma_AP,soma_DV,soma_ML,filename,name_side
293,294,3,6682.82,6054.16,2563.52,0.648438,293,8,303,BLAa,BLA,left,1,6845.74,6292.12,2574.60,251039_051,BLA_left
345,346,3,6726.18,6288.20,2571.92,0.433594,345,10,303,BLAa,BLA,left,1,6845.74,6292.12,2574.60,251039_051,BLA_left
458,459,3,6853.02,6153.94,2581.64,1.136719,458,13,303,BLAa,BLA,left,1,6845.74,6292.12,2574.60,251039_051,BLA_left
533,534,3,6754.12,6361.72,2651.54,0.324219,533,15,703,CTXsp,CTXsp,left,1,6845.74,6292.12,2574.60,251039_051,CTXsp_left
1564,1565,2,6908.06,6454.82,2923.98,0.007812,1564,17,327,BMAa,BMA,left,1,6845.74,6292.12,2574.60,251039_051,BMA_left
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60390,60391,2,5798.02,6244.84,7568.92,0.296875,60390,783,298,MA,MA,right,1,7412.10,6568.30,2227.68,252578_033,MA_right
60670,60671,2,6595.60,5804.48,8736.42,0.648438,60670,785,303,BLAa,BLA,right,1,7412.10,6568.30,2227.68,252578_033,BLA_right
60933,60934,2,6613.84,6071.88,8822.94,0.406250,60933,786,303,BLAa,BLA,right,1,7412.10,6568.30,2227.68,252578_033,BLA_right
60936,60937,2,5671.34,6270.72,7533.28,0.570312,60936,787,298,MA,MA,right,1,7412.10,6568.30,2227.68,252578_033,MA_right
60945,60946,2,5653.70,6281.14,7541.94,0.191406,60945,788,298,MA,MA,right,1,7412.10,6568.30,2227.68,252578_033,MA_right

In [44]:
dfcombine_new = dfall.pivot_table(columns="name_side",index = "filename",values="terminal",aggfunc="count").fillna(0)

In [46]:
dfcombine_new.to_excel("terminal_infor_table.xlsx")

In [38]:
dfall.pivot_table(columns="area_name",index = "filename",values="terminal",aggfunc="count").fillna(0)

area_name,AAA,ACAd1,ACAd2/3,ACAd5,ACAd6a,ACAv1,ACAv2/3,ACAv5,ACAv6a,ACAv6b,...,och,opt,or,root,rust,scwm,st,stc,unname,vtd
filename,,,,,,,,,,,,,,,,,,,,,
251038_001,0.0,2.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
251038_002,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
251038_004,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
251038_005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
251038_006,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252578_026,1.0,0.0,0.0,0.0,0.0,4.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
252578_027,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
252578_028,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
252578_029,1.0,6.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
252578_033,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0

In [41]:
dftmpnew["filename"] = filename
dftmpnew["geno"] = filename.split("_")[2]

,ID,type,AP,DV,ML,R,parent,bratch_ID,area_ID,area_name,name_use,side,terminal,soma_AP,soma_DV,soma_ML
832,833,2,5091.883789,5928.304199,5078.993652,1.078125,832,8,1109,PS,PS,left,1,5198.300781,6167.281738,5326.173828
839,840,2,5101.466797,5480.867676,5435.292969,1.285156,839,9,72,ADP,ADP,left,1,5198.300781,6167.281738,5326.173828
1859,1860,2,5089.581055,5917.661621,5085.225586,0.816406,1859,15,1109,PS,PS,left,1,5198.300781,6167.281738,5326.173828
1907,1908,2,4953.658203,5128.794434,5599.269043,0.933594,1907,17,564,MS,MS,left,1,5198.300781,6167.281738,5326.173828
2072,2073,2,5045.105957,6009.875977,5272.760742,0.847656,2072,23,523,MPO,MPO,left,1,5198.300781,6167.281738,5326.173828
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51637,51638,2,7329.959473,6263.396973,6351.452148,1.285156,51637,1309,946,PH,PH,right,1,5198.300781,6167.281738,5326.173828
51647,51648,2,7321.141602,6268.345215,6366.808594,0.992188,51647,1311,946,PH,PH,right,1,5198.300781,6167.281738,5326.173828
51649,51650,2,7326.241211,6272.154297,6361.550293,0.496094,51649,1312,946,PH,PH,right,1,5198.300781,6167.281738,5326.173828
51659,51660,2,7324.324219,6274.187500,6361.359375,1.398438,51659,1313,946,PH,PH,right,1,5198.300781,6167.281738,5326.173828
51668,51669,2,7330.738770,6284.423340,6358.826172,0.031250,51668,1314,946,PH,PH,right,1,5198.300781,6167.281738,5326.173828

In [38]:
dftmp.iloc[0,:].AP

5198.300781

C:\Users\win7\AppData\Local\Programs\Python\Python37\Lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\win7\AppData\Local\Programs\Python\Python37\Lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\win7\AppData\Local\Programs\Python\Python37\Lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [23]:
for filetmp in  files:

['180712_001_Esr1_MPN.csv',
 '180712_002_Esr1_MPN.csv',
 '180712_004_Esr1_MPN.csv',
 '180712_005_Esr1_MPN.csv',
 '180712_006_Esr1_VMPO.csv',
 '180712_007_Esr1_MPN.csv',
 '180712_008_Esr1_MPN.csv',
 '180712_021_Esr1_MPO.csv',
 '180712_022_Esr1_MPN.csv',
 '180712_023_Esr1_MPN.csv',
 '180712_024_Esr1_MPN.csv',
 '180712_025_Esr1_MPN.csv',
 '180712_026_Esr1_BST.csv',
 '180712_027_Esr1_MPN.csv',
 '180712_028_Esr1_MPN.csv',
 '180712_029_Esr1_MPN.csv',
 '180712_031_Esr1_MPN.csv',
 '180712_032_Esr1_MPN.csv',
 '180712_036_Esr1_MPN.csv',
 '180712_037_Esr1_MPN.csv',
 '180712_038_Esr1_MPN.csv',
 '180712_039_Esr1_MPO.csv',
 '180712_040_Esr1_MPO.csv',
 '180712_041_Esr1_MPN.csv',
 '180712_042_Esr1_MPN.csv',
 '180712_043_Esr1_MPN.csv',
 '180712_044_Esr1_BST.csv',
 '180712_045_Esr1_BST.csv',
 '180712_048_Esr1_HY.csv',
 '180712_050_Esr1_BST.csv',
 '180712_051_Esr1_MPN.csv',
 '180712_052_Esr1_PD.csv',
 '180712_053_Esr1_MPO.csv',
 '180712_054_Esr1_MPN.csv',
 '180712_055_Esr1_HY.csv',
 '180712_056_Esr1_MPN.csv',
 '180712_057_Esr1_MPN.csv',
 '180712_058_Esr1_MPO.csv',
 '180712_063_Esr1_MPN.csv',
 '180712_064_Esr1_MPN.csv',
 '180712_065_Esr1_MPN.csv',
 '180712_066_Esr1_MPN.csv',
 '180712_068_Esr1_MPN.csv',
 '180712_072_Esr1_MPN.csv',
 '180712_075_Esr1_MPN.csv',
 '180712_076_Esr1_MPO.csv',
 '180713_001_Esr1_LPO.csv',
 '180713_004_Esr1_BST.csv',
 '180713_005_Esr1_MPO.csv',
 '180713_006_Esr1_MPO.csv',
 '180713_007_Esr1_MPO.csv',
 '180713_015_Esr1_BST.csv',
 '180713_016_Esr1_MPO.csv',
 '180713_021_Esr1_MPO.csv',
 '180713_022_Esr1_MPO.csv',
 '180713_023_Esr1_MPO.csv',
 '180713_024_Esr1_MPN.csv',
 '180713_025_Esr1_SBPV.csv',
 '180713_030_Esr1_AHN.csv',
 '180713_031_Esr1_AHN.csv',
 '180713_035_Esr1_PVpo.csv',
 '180713_036_Esr1_MPN.csv',
 '180713_041_Esr1_MPN.csv',
 '180713_045_Esr1_HY.csv',
 '180713_047_Esr1_PD.csv',
 '180713_048_Esr1_MPO.csv',
 '180713_049_Esr1_MPN.csv',
 '180713_050_Esr1_AHN.csv',
 '180713_051_Esr1_VMPO.csv',
 '180713_052_Esr1_VMPO.csv',
 '180713_053_Esr1_AHN.csv',
 '180713_055_Esr1_VMPO.csv',
 '180713_056_Esr1_SBPV.csv',
 '180713_061_Esr1_MPN.csv',
 '180713_062_Esr1_MPN.csv',
 '180713_063_Esr1_MPN.csv',
 '180713_064_Esr1_MPO.csv',
 '180713_065_Esr1_AHN.csv',
 '180713_066_Esr1_MPN.csv',
 '180713_068_Esr1_AHN.csv',
 '180713_070_Esr1_AHN.csv',
 '180713_072_Esr1_MPN.csv',
 '180713_073_Esr1_HY.csv',
 '180713_074_Esr1_MPN.csv',
 '180713_075_Esr1_MPN.csv',
 '180713_076_Esr1_MPN.csv',
 '180713_077_Esr1_MPN.csv',
 '180713_078_Esr1_AHN.csv',
 '180713_082_Esr1_AHN.csv',
 '180713_083_Esr1_AHN.csv',
 '180713_084_Esr1_AHN.csv',
 '180713_085_Esr1_HY.csv',
 '180714_001_Esr1_MPN.csv',
 '180714_002_Esr1_MPN.csv',
 '180714_003_Esr1_MPN.csv',
 '180714_004_Esr1_MPN.csv',
 '180714_005_Esr1_MPN.csv',
 '180714_006_Esr1_MPN.csv',
 '180714_007_Esr1_MPO.csv',
 '180714_008_Esr1_MPO.csv',
 '180714_010_Esr1_MPN.csv',
 '180714_012_Esr1_HY.csv',
 '180714_013_Esr1_HY.csv',
 '180714_014_Esr1_HY.csv',
 '180714_015_Esr1_HY.csv',
 '180714_019_Esr1_MPN.csv',
 '180714_021_Esr1_MPN.csv',
 '180714_022_Esr1_MPN.csv',
 '180714_023_Esr1_MPN.csv',
 '180714_024_Esr1_MPN.csv',
 '180714_025_Esr1_MPN.csv',
 '180714_026_Esr1_PD.csv',
 '180714_027_Esr1_BST.csv',
 '180714_028_Esr1_MPN.csv',
 '180714_029_Esr1_MPO.csv',
 '180714_030_Esr1_MPO.csv',
 '180714_031_Esr1_MPO.csv',
 '180714_032_Esr1_HY.csv',
 '180714_034_Esr1_HY.csv',
 '180714_035_Esr1_HY.csv',
 '180714_036_Esr1_HY.csv',
 '180714_039_Esr1_HY.csv',
 '180714_040_Esr1_MPN.csv',
 '180714_041_Esr1_MPN.csv',
 '180714_043_Esr1_HY.csv',
 '180714_045_Esr1_MPN.csv',
 '180714_046_Esr1_HY.csv',
 '180714_047_Esr1_BST.csv',
 '180714_048_Esr1_MPO.csv',
 '180714_049_Esr1_MPO.csv',
 '180714_050_Esr1_MPN.csv',
 '180714_051_Esr1_MPN.csv',
 '180714_052_Esr1_HY.csv',
 '180714_053_Esr1_HY.csv',
 '180714_054_Esr1_MPN.csv',
 '180714_055_Esr1_MPN.csv',
 '180714_056_Esr1_MPN.csv',
 '180714_057_Esr1_MPN.csv',
 '180714_059_Esr1_HY.csv',
 '180714_062_Esr1_MPN.csv',
 '180714_063_Esr1_MPN.csv',
 '180714_065_Esr1_MPO.csv',
 '180714_067_Esr1_MPO.csv',
 '180714_069_Esr1_MPO.csv',
 '180714_070_Esr1_HY.csv',
 '180714_071_Esr1_HY.csv',
 '180714_072_Esr1_HY.csv',
 '180714_073_Esr1_HY.csv',
 '180714_074_Esr1_HY.csv',
 '180714_075_Esr1_HY.csv',
 '180714_076_Esr1_HY.csv',
 '180714_077_Esr1_MPN.csv',
 '180714_083_Esr1_MPN.csv',
 '180714_084_Esr1_MPN.csv',
 '180714_085_Esr1_MPN.csv',
 '180714_086_Esr1_MPN.csv',
 '180714_087_Esr1_MPN.csv',
 '180714_090_Esr1_MPN.csv',
 '180714_093_Esr1_MPN.csv',
 '180714_094_Esr1_MPN.csv',
 '180714_095_Esr1_MPO.csv',
 '180714_101_Esr1_MPN.csv',
 '180714_103_Esr1_MPN.csv',
 '180714_105_Esr1_MPN.csv',
 '180714_106_Esr1_MPN.csv',
 '180714_109_Esr1_MPO.csv',
 '180714_110_Esr1_MPO.csv',
 '180714_112_Esr1_PD.csv',
 '180714_113_Esr1_HY.csv',
 '180714_114_Esr1_HY.csv',
 '180714_115_Esr1_MPN.csv',
 '180714_119_Esr1_MPN.csv',
 '180714_123_Esr1_MPN.csv',
 '180714_124_Esr1_MPN.csv',
 '180714_125_Esr1_MPN.csv',
 '180714_126_Esr1_MPN.csv',
 '180714_127_Esr1_MPN.csv',
 '180714_128_Esr1_MPN.csv',
 '180715_001_Esr1_HY.csv',
 '180715_002_Esr1_HY.csv',
 '180715_004_Esr1_MPO.csv',
 '180715_005_Esr1_MPN.csv',
 '180715_007_Esr1_MPO.csv',
 '180715_009_Esr1_PD.csv',
 '180715_010_Esr1_BST.csv',
 '180715_015_Esr1_MPN.csv',
 '180715_018_Esr1_MPN.csv',
 '180715_019_Esr1_MPN.csv',
 '180715_020_Esr1_MPN.csv',
 '180715_021_Esr1_MPN.csv',
 '180715_024_Esr1_MPN.csv',
 '180715_025_Esr1_MPO.csv',
 '180715_026_Esr1_MPO.csv',
 '180715_027_Esr1_MPN.csv',
 '180715_028_Esr1_MPN.csv',
 '180715_030_Esr1_BST.csv',
 '180715_034_Esr1_BST.csv',
 '180715_039_Esr1_PD.csv',
 '180715_057_Esr1_BST.csv',
 '180715_067_Esr1_BST.csv',
 '201223_041_Nts_MPO.csv',
 '201223_043_Nts_PS.csv',
 '201223_044_Nts_HY.csv',
 '201223_046_Nts_MPO.csv',
 '201223_047_Nts_HY.csv',
 '201223_048_Nts_MPO.csv',
 '201223_049_Nts_MPO.csv',
 '201223_050_Nts_PS.csv',
 '201223_052_Nts_MPO.csv',
 '201223_053_Nts_MPN.csv',
 '201223_054_Nts_MPN.csv',
 '201223_055_Nts_AHN.csv',
 '201223_056_Nts_AHN.csv',
 '201223_057_Nts_LPO.csv',
 '201223_058_Nts_MPO.csv',
 '201223_059_Nts_LPO.csv',
 '201223_060_Nts_MPO.csv',
 '201223_061_Nts_MPO.csv',
 '201223_062_Nts_MPO.csv',
 '201223_063_Nts_MPO.csv',
 '201223_064_Nts_MPO.csv',
 '201223_065_Nts_MPO.csv',
 '201223_066_Nts_MPN.csv',
 '201223_067_Nts_MPN.csv',
 '201223_068_Nts_MPO.csv',
 '201223_069_Nts_AVP.csv',
 '201223_070_Nts_MPO.csv',
 '201223_071_Nts_MPO.csv',
 '201223_072_Nts_MPO.csv',
 '201223_073_Nts_MPN.csv',
 '201223_074_Nts_MPN.csv',
 '201223_075_Nts_BST.csv',
 '201223_076_Nts_BST.csv',
 '201223_077_Nts_MPO.csv',
 '201223_078_Nts_MPO.csv',
 '201223_089_Nts_MPO.csv',
 '201223_090_Nts_MPO.csv',
 '201223_091_Nts_MPO.csv',
 '201223_093_Nts_AVP.csv',
 '201223_111_Nts_MPN.csv',
 '201223_112_Nts_MPN.csv',
 '201223_114_Nts_MPO.csv',
 '201223_115_Nts_MPO.csv',
 '201224_001_Nts_MPO.csv',
 '201224_003_Nts_LPO.csv',
 '201224_004_Nts_LPO.csv',
 '201224_005_Nts_MPO.csv',
 '201224_006_Nts_LPO.csv',
 '201224_011_Nts_MPO.csv',
 '201224_013_Nts_BST.csv',
 '201224_014_Nts_BST.csv',
 '201224_015_Nts_MPO.csv',
 '201224_016_Nts_MPO.csv',
 '201224_017_Nts_AHN.csv',
 '201224_019_Nts_MPN.csv',
 '201224_024_Nts_MPO.csv',
 '201224_025_Nts_MPN.csv',
 '201224_026_Nts_MPO.csv',
 '201224_027_Nts_MPO.csv',
 '201224_029_Nts_LPO.csv',
 '201224_031_Nts_MPO.csv',
 '201224_033_Nts_MPO.csv',
 '201224_034_Nts_MPN.csv',
 '201224_035_Nts_LPO.csv',
 '201224_037_Nts_LPO.csv',
 '201224_041_Nts_MPO.csv',
 '201224_042_Nts_MPN.csv',
 '201224_043_Nts_MPN.csv',
 '201224_044_Nts_MPN.csv',
 '201224_045_Nts_MPO.csv',
 '201224_046_Nts_LPO.csv',
 '201224_047_Nts_PS.csv',
 '201224_048_Nts_PS.csv',
 '201224_049_Nts_MPO.csv',
 '201224_050_Nts_MPN.csv',
 '201224_051_Nts_MPN.csv',
 '201224_052_Nts_MPN.csv',
 '201224_053_Nts_MPN.csv',
 '201224_054_Nts_VLPO.csv',
 '201224_056_Nts_MPO.csv',
 '201224_057_Nts_MPO.csv',
 '201224_058_Nts_MPO.csv',
 '201224_060_Nts_AHN.csv',
 '201224_063_Nts_VMPO.csv',
 '201224_064_Nts_VMPO.csv',
 '201224_065_Nts_HY.csv',
 '201224_066_Nts_MPN.csv',
 '201224_068_Nts_AHN.csv',
 '201224_070_Nts_VMPO.csv',
 '201224_071_Nts_LPO.csv',
 '201224_073_Nts_BST.csv',
 '201224_074_Nts_MPO.csv',
 '201224_075_Nts_HY.csv',
 '201224_079_Nts_MPO.csv',
 '201224_080_Nts_MPO.csv',
 '201224_082_Nts_MPN.csv',
 '201224_083_Nts_MPN.csv',
 '201226_004_Nts_AHN.csv',
 '201226_013_Nts_MPO.csv',
 '201226_014_Nts_MPO.csv',
 '201226_015_Nts_MPO.csv',
 '201226_016_Nts_AHN.csv',
 '201226_017_Nts_AHN.csv',
 '201226_018_Nts_AHN.csv',
 '201226_019_Nts_AHN.csv',
 '201226_022_Nts_MPO.csv',
 '201226_028_Nts_VMPO.csv',
 '201226_029_Nts_MPO.csv',
 '201226_042_Nts_MPO.csv',
 '201226_043_Nts_MPN.csv',
 '201226_044_Nts_MPN.csv',
 '201226_050_Nts_LPO.csv',
 '201226_051_Nts_LPO.csv',
 '201226_052_Nts_LPO.csv',
 '201226_054_Nts_BST.csv',
 '201226_056_Nts_HY.csv',
 '201226_063_Nts_HY.csv',
 '201226_067_Nts_MPN.csv',
 '201226_079_Nts_MPN.csv',
 '201226_080_Nts_MPN.csv',
 '201226_081_Nts_MPN.csv',
 '201226_082_Nts_MPO.csv',
 '201226_083_Nts_HY.csv',
 '201226_088_Nts_MPO.csv',
 '201226_090_Nts_VMPO.csv',
 '201227_001_Nts_VMPO.csv',
 '201227_002_Nts_PD.csv',
 '201227_003_Nts_MPO.csv',
 '201227_004_Nts_MPN.csv',
 '201227_005_Nts_MPN.csv',
 '201227_006_Nts_MPN.csv',
 '201227_007_Nts_MPO.csv',
 '201227_008_Nts_MPO.csv',
 '201227_009_Nts_MPO.csv',
 '201227_010_Nts_MPN.csv',
 '201227_011_Nts_MPN.csv',
 '201227_012_Nts_HY.csv',
 '201227_013_Nts_MPN.csv',
 '201227_014_Nts_MPO.csv',
 '201227_015_Nts_MPO.csv',
 '201227_016_Nts_MPO.csv',
 '201227_017_Nts_HY.csv',
 '201227_018_Nts_MPN.csv',
 '201227_019_Nts_MPN.csv',
 '201227_020_Nts_MPO.csv',
 '201227_021_Nts_HY.csv',
 '201227_022_Nts_BST.csv',
 '201227_023_Nts_MPN.csv',
 '201227_025_Nts_AHN.csv',
 '201227_026_Nts_MPO.csv',
 '201227_027_Nts_MPO.csv',
 '201227_028_Nts_LPO.csv',
 '201227_029_Nts_MPO.csv',
 '201227_030_Nts_MPO.csv',
 '201227_032_Nts_LPO.csv',
 '201227_033_Nts_PD.csv',
 '201227_034_Nts_MPO.csv',
 '201227_036_Nts_HY.csv',
 '201227_037_Nts_MPN.csv',
 '201227_038_Nts_MPO.csv',
 '201227_039_Nts_BST.csv',
 '201227_040_Nts_MPO.csv',
 '201227_041_Nts_MPO.csv',
 '201228_004_Nts_VMPO.csv',
 '201228_005_Nts_MPO.csv',
 '201228_007_Nts_BST.csv',
 '201228_008_Nts_HY.csv',
 '201228_009_Nts_MPO.csv',
 '201228_010_Nts_MPN.csv',
 '201228_011_Nts_MPO.csv',
 '201228_013_Nts_MPN.csv',
 '201228_014_Nts_MPN.csv',
 '201228_015_Nts_MPN.csv',
 '201228_016_Nts_MPN.csv',
 '201228_017_Nts_MPO.csv',
 '201228_018_Nts_BST.csv',
 '201228_019_Nts_MPO.csv',
 '201228_020_Nts_HY.csv',
 '201228_021_Nts_MPO.csv',
 '201228_022_Nts_MPN.csv',
 '201228_023_Nts_AHN.csv',
 '201228_024_Nts_MPN.csv',
 '201228_025_Nts_VMPO.csv',
 '201228_026_Nts_MPN.csv',
 '201228_027_Nts_MPN.csv',
 '201228_029_Nts_MPN.csv',
 '201228_030_Nts_MPN.csv',
 '201228_031_Nts_MPO.csv',
 '201228_032_Nts_MPN.csv',
 '201228_033_Nts_MPO.csv',
 '201228_034_Nts_MPO.csv',
 '201228_036_Nts_MPO.csv',
 '201228_037_Nts_MPO.csv',
 '201228_038_Nts_MPO.csv',
 '201228_039_Nts_MPO.csv',
 '201228_040_Nts_LPO.csv',
 '201228_041_Nts_MPO.csv',
 '201228_042_Nts_VMPO.csv',
 '201228_043_Nts_MPO.csv',
 '201228_044_Nts_MPN.csv',
 '201228_045_Nts_MPO.csv',
 '201228_048_Nts_BST.csv',
 '201228_049_Nts_MPO.csv',
 '201228_051_Nts_LPO.csv',
 '201228_052_Nts_AVP.csv',
 '201228_054_Nts_LPO.csv',
 '201228_055_Nts_HY.csv',
 '201228_056_Nts_MPO.csv',
 '201228_057_Nts_BST.csv',
 '201228_058_Nts_BST.csv',
 '201228_060_Nts_MPN.csv',
 '201228_062_Nts_MPN.csv',
 '201229_052_Tac1_MPN.csv',
 '201229_059_Tac1_MPN.csv',
 '201229_060_Tac1_MPN.csv',
 '201229_061_Tac1_MPN.csv',
 '201229_062_Tac1_MPN.csv',
 '201229_063_Tac1_MPN.csv',
 '201229_064_Tac1_MPN.csv',
 '201229_098_Tac1_AHN.csv',
 '201229_100_Tac1_LPO.csv',
 '201229_101_Tac1_HY.csv',
 '201229_136_Tac1_MPN.csv',
 '201229_137_Tac1_MPO.csv',
 '201229_138_Tac1_MPO.csv',
 '201229_153_Tac1_BST.csv',
 '201229_156_Tac1_HY.csv',
 '201229_157_Tac1_MPO.csv',
 '201229_170_Tac1_MPO.csv',
 '201229_178_Tac1_AHN.csv',
 '201229_182_Tac1_MPN.csv',
 '201230_009_Tac1_LPO.csv',
 '201230_069_Tac1_HY.csv',
 '201578_003_Nts_HY.csv',
 '201578_004_Nts_HY.csv',
 '201578_083_Nts_AHN.csv',
 '201578_092_Nts_AHN.csv',
 '201789_021_Pdyn_HY.csv',
 '201793_053_Pdyn_HY.csv',
 '201793_056_Pdyn_MPN.csv',
 '201793_057_Pdyn_MPN.csv',
 '201793_064_Pdyn_MPN.csv',
 '201895_001_Tac2_MPO.csv',
 '201895_002_Tac2_HY.csv',
 '201895_003_Tac2_BST.csv',
 '201895_004_Tac2_LPO.csv',
 '201895_005_Tac2_MPO.csv',
 '201895_006_Tac2_BST.csv',
 '201895_007_Tac2_BST.csv',
 '201895_012_Tac2_BST.csv',
 '201895_014_Tac2_LPO.csv',
 '201895_016_Tac2_LPO.csv',
 '201895_017_Tac2_MPO.csv',
 '201895_018_Tac2_MPN.csv',
 '201895_020_Tac2_MPO.csv',
 '201895_024_Tac2_MPN.csv',
 '201895_025_Tac2_MPN.csv',
 '201895_031_Tac2_MPN.csv',
 '201895_032_Tac2_AHN.csv',
 '201895_033_Tac2_AHN.csv',
 '201895_034_Tac2_LPO.csv',
 '201895_036_Tac2_MPN.csv',
 '201895_038_Tac2_MPO.csv',
 '201895_039_Tac2_BST.csv',
 '201895_041_Tac2_MPN.csv',
 '201896_002_Tac2_MPO.csv',
 '201896_003_Tac2_VMPO.csv',
 '201896_004_Tac2_MPN.csv',
 '201896_006_Tac2_MPN.csv',
 '201896_007_Tac2_MPN.csv',
 '201896_008_Tac2_MPN.csv',
 '201896_009_Tac2_MPN.csv',
 '201896_010_Tac2_MPN.csv',
 '201896_011_Tac2_AVPV.csv',
 '201896_012_Tac2_MPN.csv',
 '201896_013_Tac2_MPN.csv',
 '201922_001_Nts_MPN.csv',
 '201922_002_Nts_MPO.csv',
 '201922_003_Nts_MPO.csv',
 '201922_005_Nts_MPO.csv',
 '201922_006_Nts_MPO.csv',
 '201922_008_Nts_MPO.csv',
 '201922_012_Nts_MPN.csv',
 '201922_013_Nts_MPN.csv',
 '201922_015_Nts_MPN.csv',
 '201922_023_Nts_MPN.csv',
 '201922_028_Nts_MPN.csv',
 '201922_031_Nts_MPN.csv',
 '201922_032_Nts_MPN.csv',
 '201922_033_Nts_MPN.csv',
 '201922_034_Nts_MPN.csv',
 '201922_036_Nts_MPO.csv',
 '201922_037_Nts_ADP.csv',
 '201922_040_Nts_MPO.csv',
 '201922_041_Nts_AVP.csv',
 '201922_042_Nts_MPO.csv',
 '201922_044_Nts_AHN.csv',
 '201922_054_Nts_AHN.csv',
 '201922_055_Nts_HY.csv',
 '201922_056_Nts_VLPO.csv',
 '201922_059_Nts_LPO.csv',
 '201922_060_Nts_MPO.csv',
 '201922_061_Nts_MPO.csv',
 '201922_062_Nts_MPO.csv',
 '201922_063_Nts_HY.csv',
 '201922_064_Nts_BST.csv',
 '201922_065_Nts_BST.csv',
 '201922_066_Nts_BST.csv',
 '201922_070_Nts_MPO.csv',
 '201922_071_Nts_MPO.csv',
 '201922_072_Nts_MPO.csv',
 '201922_073_Nts_MPO.csv',
 '201922_074_Nts_MPN.csv',
 '201922_082_Nts_BST.csv',
 '201922_083_Nts_HY.csv',
 '201922_084_Nts_MPO.csv',
 '201922_085_Nts_MPO.csv',
 '201923_087_Nts_BST.csv',
 '201924_002_Nts_HY.csv',
 '201924_003_Nts_MPN.csv',
 '201924_004_Nts_VMPO.csv',
 '201924_005_Nts_AHN.csv',
 '201924_006_Nts_AHN.csv',
 '201924_014_Nts_AHN.csv',
 '201924_016_Nts_AHN.csv',
 '201924_019_Nts_MPO.csv',
 '201924_020_Nts_MPN.csv',
 '201924_021_Nts_LPO.csv',
 '201924_022_Nts_HY.csv',
 '201924_023_Nts_MPO.csv',
 '201924_024_Nts_MPO.csv',
 '201924_025_Nts_AHN.csv',
 '201924_027_Nts_VMPO.csv',
 '201924_028_Nts_MPN.csv',
 '201924_029_Nts_MPN.csv',
 '201924_030_Nts_MPO.csv',
 '201924_031_Nts_AHN.csv',
 '201924_032_Nts_MPN.csv',
 '201924_033_Nts_HY.csv',
 '201924_035_Nts_MPO.csv',
 '201924_036_Nts_AHN.csv',
 '201924_037_Nts_MPO.csv',
 '201924_038_Nts_VMPO.csv',
 '201924_039_Nts_MPN.csv',
 '201924_042_Nts_MPN.csv',
 '201924_044_Nts_MPN.csv',
 '201924_045_Nts_VMPO.csv',
 '201924_046_Nts_AHN.csv',
 '201924_047_Nts_LPO.csv',
 '201924_049_Nts_MPO.csv',
 '201924_052_Nts_VMPO.csv',
 '201924_054_Nts_MPO.csv',
 '201924_055_Nts_MPO.csv',
 '201924_056_Nts_MPO.csv',
 '201924_057_Nts_LPO.csv',
 '201924_058_Nts_MPO.csv',
 '201924_059_Nts_HY.csv',
 '201924_062_Nts_MPO.csv',
 '201924_065_Nts_MPN.csv',
 '201924_068_Nts_MPN.csv',
 '201924_070_Nts_MPO.csv',
 '201924_073_Nts_AHN.csv',
 '201924_076_Nts_MPN.csv',
 '201924_077_Nts_AHN.csv',
 '201924_079_Nts_MPO.csv',
 '201924_087_Nts_AHN.csv',
 '201924_088_Nts_HY.csv',
 '201924_090_Nts_AHN.csv',
 '201924_092_Nts_MPN.csv',
 '201924_093_Nts_MPN.csv',
 '201924_095_Nts_AHN.csv',
 '201924_096_Nts_AHN.csv',
 '201924_097_Nts_HY.csv',
 '201924_098_Nts_MPO.csv',
 '201924_099_Nts_VLPO.csv',
 '201924_100_Nts_VLPO.csv',
 '201924_102_Nts_VLPO.csv',
 '201924_103_Nts_LPO.csv',
 '201924_104_Nts_AVP.csv',
 '201924_105_Nts_LPO.csv',
 '201924_108_Nts_MPO.csv',
 '201924_109_Nts_MPO.csv',
 '201924_110_Nts_MPO.csv',
 '201924_141_Nts_MPO.csv',
 '201924_142_Nts_LPO.csv',
 '201924_143_Nts_LPO.csv',
 '201924_144_Nts_LPO.csv',
 '201924_145_Nts_LPO.csv',
 '201924_156_Nts_MPN.csv',
 '201925_001_Nts_MPN.csv',
 '201925_003_Nts_AHN.csv',
 '201925_004_Nts_AHN.csv',
 '201925_006_Nts_VMPO.csv',
 '201925_007_Nts_HY.csv',
 '201925_009_Nts_HY.csv',
 '201925_010_Nts_PD.csv',
 '201925_015_Nts_BST.csv',
 '201925_016_Nts_PD.csv',
 '201925_018_Nts_MPO.csv',
 '201925_020_Nts_HY.csv',
 '201925_021_Nts_MPN.csv',
 '201925_022_Nts_MPN.csv',
 '201925_023_Nts_MPO.csv',
 '201925_024_Nts_MPO.csv',
 '201925_025_Nts_MPO.csv',
 '201925_026_Nts_MPN.csv',
 '201925_027_Nts_MPN.csv',
 '201925_028_Nts_MPN.csv',
 '201925_029_Nts_MPN.csv',
 '201925_030_Nts_MPN.csv',
 '201925_031_Nts_MPN.csv',
 '201925_032_Nts_MPN.csv',
 '201925_033_Nts_MPN.csv',
 '201925_034_Nts_MPN.csv',
 '201925_036_Nts_MPO.csv',
 '201925_037_Nts_MPO.csv',
 '201925_040_Nts_MPO.csv',
 '201925_041_Nts_BST.csv',
 '201925_042_Nts_MPO.csv',
 '201925_067_Nts_HY.csv',
 '201925_068_Nts_HY.csv',
 '201925_069_Nts_HY.csv',
 '201925_070_Nts_PD.csv',
 '201925_071_Nts_HY.csv',
 '201925_072_Nts_MPN.csv',
 '201925_073_Nts_PD.csv',
 '201925_074_Nts_MPO.csv',
 '201925_075_Nts_HY.csv',
 '201925_076_Nts_MPO.csv',
 '201925_077_Nts_HY.csv',
 '201925_078_Nts_HY.csv',
 '201925_079_Nts_AHN.csv',
 '201925_082_Nts_VLPO.csv',
 '201925_083_Nts_MPO.csv',
 '201925_086_Nts_MPN.csv',
 '201925_087_Nts_MPN.csv',
 '201925_088_Nts_MPN.csv',
 '201925_089_Nts_HY.csv',
 '201925_090_Nts_HY.csv',
 '201925_091_Nts_HY.csv',
 '201925_103_Nts_AHN.csv',
 '202168_047_Penk_LPO.csv',
 '202168_048_Penk_LPO.csv',
 '202168_050_Penk_LPO.csv',
 '202455_011_Penk_LPO.csv',
 '202455_012_Penk_MPO.csv',
 '202455_013_Penk_AHN.csv',
 '202455_014_Penk_HY.csv',
 '202455_015_Penk_MPO.csv',
 '202455_016_Penk_MPO.csv',
 '202455_018_Penk_VLPO.csv',
 '202455_021_Penk_HY.csv',
 '202455_022_Penk_MPO.csv',
 '202455_023_Penk_AVP.csv',
 '202455_024_Penk_MPO.csv',
 '202455_026_Penk_AVP.csv',
 '202455_027_Penk_MPO.csv',
 '202455_028_Penk_AVP.csv',
 '202455_029_Penk_MPO.csv',
 '202455_038_Penk_MPO.csv',
 '202455_039_Penk_LPO.csv',
 '202455_059_Penk_MPO.csv',
 '202455_061_Penk_AVP.csv',
 '202455_062_Penk_MPO.csv',
 '202455_064_Penk_AVP.csv',
 '202455_065_Penk_MPO.csv',
 '202455_078_Penk_MPO.csv',
 '202455_080_Penk_MPO.csv',
 '202455_081_Penk_MPO.csv',
 '202455_082_Penk_MPO.csv',
 '202455_095_Penk_MPO.csv',
 '202455_096_Penk_MPO.csv',
 '202455_097_Penk_MPO.csv',
 '202455_110_Penk_MPO.csv',
 '202455_111_Penk_MPO.csv',
 '202455_112_Penk_MPO.csv',
 '202455_134_Penk_HY.csv',
 '202455_135_Penk_HY.csv',
 '202455_136_Penk_MPO.csv',
 '202455_137_Penk_AVP.csv',
 '202455_141_Penk_MPO.csv',
 '202455_142_Penk_AVPV.csv',
 '202455_144_Penk_AVP.csv',
 '202455_145_Penk_MPO.csv',
 '202455_147_Penk_MPO.csv',
 '202455_149_Penk_MPO.csv',
 '202456_001_Penk_MPO.csv',
 '202456_002_Penk_HY.csv',
 '202456_003_Penk_LPO.csv',
 '202456_005_Penk_MPO.csv',
 '202456_007_Penk_AVP.csv',
 '202456_008_Penk_MPO.csv',
 '202456_015_Penk_MPO.csv',
 '202456_017_Penk_MPO.csv',
 '202456_020_Penk_MPO.csv',
 '202456_022_Penk_MPO.csv',
 '202456_024_Penk_MPO.csv',
 '202456_025_Penk_MPO.csv',
 '202456_026_Penk_AVP.csv',
 '202456_065_Penk_AVP.csv',
 '202456_066_Penk_MPO.csv',
 '202456_067_Penk_LPO.csv',
 '202456_068_Penk_AVP.csv',
 '202456_069_Penk_MPO.csv',
 '202560_002_Tac2_LPO.csv',
 '202560_004_Tac2_HY.csv',
 '202560_005_Tac2_LPO.csv',
 '202560_007_Tac2_MPO.csv',
 '202560_009_Tac2_HY.csv',
 '202560_010_Tac2_BST.csv',
 '202560_013_Tac2_BST.csv',
 '202560_015_Tac2_BST.csv',
 '202560_016_Tac2_BST.csv',
 '202560_017_Tac2_MPN.csv',
 '202560_018_Tac2_MPN.csv',
 '202560_020_Tac2_MPO.csv',
 '202560_021_Tac2_MPO.csv',
 '202560_058_Tac2_HY.csv',
 '202561_003_Tac2_MPO.csv',
 '202561_004_Tac2_MPN.csv',
 '202561_005_Tac2_AHN.csv',
 '202561_006_Tac2_AHN.csv',
 '202561_007_Tac2_AHN.csv',
 '202561_017_Tac2_HY.csv',
 '202561_048_Tac2_AHN.csv',
 '202570_015_Penk_MPO.csv',
 '202570_065_Penk_AVP.csv',
 '202570_078_Penk_HY.csv',
 '202570_079_Penk_AVP.csv',
 '202570_089_Penk_AVP.csv',

In [11]:
if dftmp.parent.unique()

array([   -1,     1,     2, ..., 51666, 51667, 51668], dtype=int64)

In [19]:
dftmp["terminal"] = [0 if item in dftmp.parent.unique() else 1 for item in dftmp.ID.tolist()]

In [18]:
inlist = dftmp.parent.unique()
IDlist = dftmp.ID.tolist()
dftmp["terminal"] = [0 if item in inlist else 1 for item in IDlist]

In [16]:
dftmp

,ID,type,AP,DV,ML,R,parent,bratch_ID,area_ID,area_name,name_use,side,terminal
0,1,1,5198.300781,6167.281738,5326.173828,3.414063,-1,1,515,MPN,MPN,left,0
1,2,2,5196.447266,6167.419434,5326.122559,2.042969,1,1,515,MPN,MPN,left,0
2,3,2,5194.444336,6166.463867,5325.943359,0.933594,2,1,523,MPO,MPO,left,0
3,4,2,5193.116211,6164.957520,5325.913574,1.136719,3,1,523,MPO,MPO,left,0
4,5,2,5191.160645,6163.651855,5326.088867,0.496094,4,1,523,MPO,MPO,left,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51664,51665,2,7328.383301,6280.264648,6361.663086,0.960938,51664,1314,946,PH,PH,right,0
51665,51666,2,7329.422363,6280.909180,6360.434082,0.320313,51665,1314,946,PH,PH,right,0
51666,51667,2,7329.641602,6281.489746,6359.133789,0.757813,51666,1314,946,PH,PH,right,0
51667,51668,2,7330.269043,6283.376465,6358.964844,0.816406,51667,1314,946,PH,PH,right,0
51668,51669,2,7330.738770,6284.423340,6358.826172,0.031250,51668,1314,946,PH,PH,right,1

In [12]:
dftmp

,ID,type,AP,DV,ML,R,parent,bratch_ID,area_ID,area_name,name_use,side
0,1,1,5198.300781,6167.281738,5326.173828,3.414063,-1,1,515,MPN,MPN,left
1,2,2,5196.447266,6167.419434,5326.122559,2.042969,1,1,515,MPN,MPN,left
2,3,2,5194.444336,6166.463867,5325.943359,0.933594,2,1,523,MPO,MPO,left
3,4,2,5193.116211,6164.957520,5325.913574,1.136719,3,1,523,MPO,MPO,left
4,5,2,5191.160645,6163.651855,5326.088867,0.496094,4,1,523,MPO,MPO,left
...,...,...,...,...,...,...,...,...,...,...,...,...
51664,51665,2,7328.383301,6280.264648,6361.663086,0.960938,51664,1314,946,PH,PH,right
51665,51666,2,7329.422363,6280.909180,6360.434082,0.320313,51665,1314,946,PH,PH,right
51666,51667,2,7329.641602,6281.489746,6359.133789,0.757813,51666,1314,946,PH,PH,right
51667,51668,2,7330.269043,6283.376465,6358.964844,0.816406,51667,1314,946,PH,PH,right
51668,51669,2,7330.738770,6284.423340,6358.826172,0.031250,51668,1314,946,PH,PH,right